### ISSUE TITLE
React Rotterdam. First meetup of 2020. Call for speakers.

### ISSUE THREAD

**Issue by zubivan** [reactrotterdam/meetup#5]
Hello everyone,

Our first winter meetup is almost scheduled, so it's time to look forward for the next edition! And looks like it's going to be in 2020! 

Since we promised we are going to try to host our meetups more regularly and that means that... CALL FOR SPEAKERS is open.

If you want to present on one of our next meetups (or know someone who wants!) or feel like doing a lightning talk, please submit a comment under this issue in the following format:

👋NAME
✍️TALK TITLE
📖SHORT ABSTRACT
📜 SHORT BIO

Otherwise, feel free to reach out via the usual channels that you can find https://github.com/reactrotterdam/meetup#contributing.

**Comment by wilcoschoneveld** [comment]
👋Wilco Schoneveld
✍️Building user interfaces with finite state machines

📖How do state machines work and how can they contribute to a robust and scalable user interface? How does it compare to other state management approaches? In this talk I will dive into the world of statecharts and explore its potential and limits for use in frontend applications. I will give concrete examples with React & XState and show how to split up the application logic into multiple machines with the Actor model.

**Comment by mauricedb** [comment]
👋 Maurice de Beijer

✍️ React Suspense, not just for Alfred Hitchcock

📖 The React team has rewritten the book on developing components several times. This time they have introduced Suspense. Amongst other thing this makes splitting your application into multiple bundles easier. But that is only the start as the real innovation comes when loading data. Gone are the side effect hooks with the typical loading, loaded and error states. Instead we can suspend components when loading data. Need to do multiple request? No problem you can suspend multiple components at the same time if you want. Need to trap errors? No problem just use a standard React error boundary. Come to this session to learn what React Suspense can do for you. 

📜 Maurice de Beijer is an independent software consultant and trainer. He specializes in JavaScript, React, and ASP.NET Core. His work includes a large, global, safety application for the oil and gas industry. Maurice is also active in the open source community. He teaches ECMAScript, TypeScript, React, RxJS and ASP.NET courses. Since 2005, he has received Microsoft’s Yearly Most Valuable Professional Award. Maurice is also active in the Dutch dotNed user group and helps organize its meetings

**Comment by zubivan** [comment]
Hoho! Amazing! I think we have a lineup for 2020 already! 

@wilcoschoneveld @mauricedb Shall we do it sometime at the end of January?

**Comment by wilcoschoneveld** [comment]
Yes, week of 27th of January or later would work best for me

**Comment by mauricedb** [comment]
That works for me as well.

**Comment by zubivan** [comment]
I think we have a date! I'll create a draft event and let you know once it's out there.

**Comment by zubivan** [comment]
@wilcoschoneveld @mauricedb will 29th or 30th work for you?

**Comment by mauricedb** [comment]
Both dates work for me with a very slight preference for Wednesday the 29th.

**Comment by wilcoschoneveld** [comment]
Both dates is fine

**Comment by zubivan** [comment]
And finally there we go! I'll shoot with the announcement a bit later.

https://www.meetup.com/React-Rotterdam/events/266520214

**Comment by wilcoschoneveld** [comment]
Awesome! I'm looking forward to it

**Comment by wilcoschoneveld** [comment]
@zubivan quick bio: Wilco Schoneveld is a full stack developer with a background in innovation, data science and aerospace engineering. He is employed as a consultant at HeadFWD and has worked for both start-ups and organisations such as Deloitte and Rabobank.

thanks!

**Comment by zubivan** [comment]
@wilcoschoneveld Updated! Khm, spent last couple of weeks almost without touching my laptop, sorry for the delay.

@wilcoschoneveld @mauricedb all ready for this Wednesday? 🚀

**Comment by mauricedb** [comment]
@zubivan Yup all prepped and ready to go 😄 Are you going to record the sessions and publish them to YouTube?

**Comment by wilcoschoneveld** [comment]
Yes! Finished my slides today. I'm aiming for 40 minute presentation :)

**Comment by zubivan** [comment]
@wilcoschoneveld looking forward to it!

@mauricedb we will try to setup recordings, but not yet sure we're going to post it online. I'm considering starting online webinars for React.Rotterdam, so people from outside can join. Do you think it might be useful?

**Comment by mauricedb** [comment]
@zubivan There are plenty of people who are not in the opportunity to attend who might want to watch session like this online after they where recorded. I for one watch a fair number of sessions on YouTube and would never be able to attend all of them.

**Comment by wilcoschoneveld** [comment]
@zubivan are the talk recordings online yet? thanks!
